### ISSUE TITLE
botpress-irc Module on OSX issues

### ISSUE THREAD

**Issue by DonRichards** [TheFreakLord/botpress-irc#1]
#### Had an error with installing **botpress-rc** module. 

When I click on it the page says Loading module... And it stays like this.
![000](https://cloud.githubusercontent.com/assets/2738244/23303244/f004ac34-fa60-11e6-9f1f-30f72f56f30d.png)

#### Here's my error Log 

[https://gist.github.com/DonRichards/e549506917660f6b98271888354f0816](https://gist.github.com/DonRichards/e549506917660f6b98271888354f0816)

#### My Environment: 
- OSX Sierra 10.12.3
- node v7.5.0
- npm  4.2.0 ![420](http://www.drreeferalz.com/wp-content/themes/reeferalz/favicon.png)

### EDITED:
The error comes at node-icu-charset-detector@0.2.0 install

ICU4C libraries should fill in this gaps. One way to knock out this error but causes another is to do the following. 
```terminal
brew install icu4c
brew link --overwrite icu4c --force
```
Here's the new log
[https://gist.github.com/DonRichards/1739b6539d82fd163239c4f3faaf692e](https://gist.github.com/DonRichards/1739b6539d82fd163239c4f3faaf692e)

Current Error
```bash
error: ## Using --prefix=/usr/local/bin//..
```

Not sure what it's trying to do here. But the error message isn't that helpful.

The module still says "**Loading module....**"

**Comment by MagnificentPako** [comment]
The fact that it says "Loading module..." isn't a bug. botpress-irc has no frontend you could interact with so I left the example files unchanged, which leads to this behavior. You should still be able to connect to a server and listen for irc messages.

I personally don't have any experience with OSX so I unfortunately can't help you with the icu problem. It appears to be loading botpress-irc without it though, so I hope it won't be a module-breaking dependency.

**Comment by paos** [comment]
@TheFreakLord Can you make oneliner frontpage? It is very confusing when you get a loading screen that never completes, and it it is something that signals an error.

**Comment by MagnificentPako** [comment]
@paos instead of adding a oneliner interface which does nothing I opted for disabled the interface completely. It shouldn't appear in your menu anymore now (since version 2.0.1)

**Comment by DonRichards** [comment]
I'm closing this. There doesn't seem to be development on this repo any more and this is showing up in my list of open tickets.
